boltpkg/bolt

src/utils/yarn.js

I ran into a bunch of issues with preinstall and postinstall scripts not being present.
We are getting the same issue in CI too. For Trey, it seems to happen in node 8.4.0 and not 8.1.4. 
It seems to happen to me in both versions (and CI is running 8.1.4).
In either case this seemed logical?

Prevents running scripts in packages if they don't exist

---

src/utils/getUnpublishedPackages.js

This was running serially, this should speed it up quite a bit
@lukebatchelor

Run npm.info in getUnpublishedPackages in parallel

---

src/Config.js
src/Project.js
src/__fixtures__/nested-workspaces-transitive-dependents/packages/workspace-a/package.json
src/__fixtures__/nested-workspaces-with-scoped-package-names/packages/foo/package.json
src/__fixtures__/nested-workspaces/packages/foo/package.json
src/__tests__/Config.test.js
src/utils/globs.js

This changes the way workspaces are specified to work of the cwd of the package that specifies them:
```json
{
"pworkspaces": [
"foo"
]
}
```
Previously would match:
```
/project/foo
/project/nested/dir/foo
```
But will now only match
```
/project/foo
```
Also creates a new `globs` util to use instead of `multimatch` or `globby` directly.
---
Edit: all of the above was incorrect, I just had made a dumb mistake in `getWorkspaces()`

Workspaces are specified absolutely from project cwd, create globs util

---

src/Project.js
src/cli.js
src/commands/install.js
src/commands/normalize.js
src/commands/publish.js
src/commands/run.js
src/utils/locks.js
src/utils/logger.js
src/utils/messages.js
src/utils/npm.js
src/utils/removeDependenciesFromPackages.js
src/utils/yarn.js

You are now forced to write:
```js
logger.error(messages.didntWork())
```
This will cause a type error:
```js
logger.error(`Didn't work`);
// string. This type is incompatible with the expected param type of opaque type `Message`
```
I also added a bunch of emojis to the CLI, and I split out some logic from `yarn.run` to `yarn.getScript` so we could add messages for missing scripts elsewhere.

Rework messages/logger to use opaque type, add emojis, rework running scripts to add message

---

src/commands/__tests__/install.test.js
src/commands/workspaces/run.js
src/utils/__tests__/symlinkPackageDependencies.test.js
src/utils/removeDependenciesFromPackages.js
src/utils/symlinkPackageDependencies.js
src/utils/yarn.js

I introduced a regression with the bolt add when I refactored the install script to use my symlinkPakckages helper.
I've added `yarn.runIfExists` to wrap the behaviour where you dont want to error if the script doesnt exist. So, things like lifecycle events and `workspaces run`.

Adds yarn.runIfExists

---

src/Config.js
src/utils/logger.js
src/utils/messages.js

This PR does two things:
- Fixes the logger rendering of emoji so they are prefixed to each line, not just the first line
- Displays a helpful error message indicating which json file had an error when `parse-json` throws an error of type `JSONError`
The second fix means that if you have a syntax error in one of your `package.json` files, it will now tell you which one.

Make JSON parser errors easier to identify

---

src/Config.js
src/Package.js
src/utils/messages.js

I found this problem after switching branches in a bolt repo, where an empty package directory had been left behind because it had an ignored `node_modules` in it.
The default "could not find package.json" error (code `ENOENT`) was really unhelpful, because I didn't realise the directory remained, and couldn't find any code referencing the missing file.
I added a nicer error message so that if (when) this happens to others, they understand why it may have happened and how to resolve it.

Better errors with missing package.json

---

src/functions/__tests__/updatePackageVersions.test.js
src/functions/updatePackageVersions.js

As in title. This is to allow us to bump internal versions only when required.
Note: This is a breaking change from current API.

Updates bolt.updatePackageVersions to not automatically add a caret

---

src/functions/__fixtures__/lots-of-internally-linked-deps/package.json
src/functions/__fixtures__/lots-of-internally-linked-deps/packages/caret-dep/package.json
src/functions/__fixtures__/lots-of-internally-linked-deps/packages/has-all-deps-with-peers/package.json
src/functions/__fixtures__/lots-of-internally-linked-deps/packages/has-all-deps/package.json
src/functions/__fixtures__/lots-of-internally-linked-deps/packages/pinned-dep/package.json
src/functions/__fixtures__/lots-of-internally-linked-deps/packages/tilde-dep/package.json
src/functions/__tests__/updatePackageVersions.test.js
src/functions/updatePackageVersions.js
src/utils/messages.js

* updatePackageVersions now supports bumping packages with caret and tilde ranges
* BREAKING: it will no longer support bumping external deps and will warn if you attempt to
We could rename this at some point, but I think this greatly simplifies the functions purpose:
"An external tool has bumped your versions, run this function to get all your internal versions back in to line"
It should be noted though, it only bumps the ones you've told it to, and doesnt perform any validation of what you've passed in, besides excluding  external deps.

Changes updatePackageVersions to work with ranges

---

src/utils/execCommand.js

Before:
```sh
$ tsc --project ./build/es5 src/ui/MediaItem/MediaComponent.tsx(237,27): error TS2339: Property 'src' does not exist on type 'Blob'.
```
After: 
```sh
(@atlaskit/editor-common) $ tsc --project ./build/es5 src/ui/MediaItem/MediaComponent.tsx(237,27): error TS2339: Property 'src' does not exist on type 'Blob'.
```

Pass pkg to processes.spawn from execCommand

---

src/commands/workspace/__tests__/run.test.js
src/utils/yarn.js

Output was looking like this
```
(@atlaskit/fabric) $ /usr/local/share/.config/yarn/global/node_modules/bolt/node_modules/.bin/yarn run -s release RELEASING: Releasing 1 package(s)
(@atlaskit/fabric) $ /usr/local/share/.config/yarn/global/node_modules/bolt/node_modules/.bin/yarn run -s release 
(@atlaskit/fabric) $ /usr/local/share/.config/yarn/global/node_modules/bolt/node_modules/.bin/yarn run -s release Releases:
(@atlaskit/fabric) $ /usr/local/share/.config/yarn/global/node_modules/bolt/node_modules/.bin/yarn run -s release   @atlaskit/conversation@4.6.0
(@atlaskit/fabric) $ /usr/local/share/.config/yarn/global/node_modules/bolt/node_modules/.bin/yarn run -s release 
(@atlaskit/fabric) $ /usr/local/share/.config/yarn/global/node_modules/bolt/node_modules/.bin/yarn run -s release …
```

Makes yarn run output display relative path to yarn instead of absolute

---

src/commands/add.js
src/commands/project/__tests__/add.test.js
src/commands/project/add.js
src/utils/addDependenciesToPackages.js
src/utils/processes.js

For basic usage, this works really well, like adding the dependency. I have two questions here,
1. What do we have to do when we add the new dependency that is already present in the package? Simply install them? (into the project) I would opt for this given the fact that anybody can go into the project and install the dependencies using `yarn or npm`. 
2. Do we need to keep track of the specific project related dependencies somewhere? In order to make update to be written easier? I would say no to it, since this will create a lot of edge cases.

Adding Project add <dependency>

---

src/Package.js
src/functions/updateWorkspaceDependencies.js

Fixes bug where packages with a dep and a devDep on a package would not be able to upgrade that dep
This *should* have been caught by flow, but wasn't because of the issue we are seeing with the type inference.
I looked at adding a test for this, but it's a pain because of how the upgrade tests are set up (my bad). There's already a refactor going on in that area, so happy to wait till after that.

Fixes bolt upgrade with multiple depTypes

---

src/commands/__tests__/install.test.js
src/commands/install.js
src/utils/__tests__/yarn.test.js
src/utils/processes.js
src/utils/yarn.js

Turns our we never actually made bolt install use the local one at all.
Change was quite simple, tests were a pain to refactor, but I think they are a lot cleaner now.
I also fixed the issue with the long paths being shows in the logs by adding a 'useBasename' flag to spawn and turning that on for `yarn install`, and all `yarn run` commands.
I couldnt properly test that locally for some reason, `bolt install` for example wouldnt show the command in the front of the logs. But it should be safe to test in CI either way.

Fixes bolt install to use local yarn instead of global

---

src/utils/messages.js

It now looks something like this:
I realised whilst looking at this that we probably shouldnt have that error message in bolt itself because it assumes the existance of changesets. Im happy to leave for now though until `bolt` has a blessed way of handling this (it'll be a minor text change).

Updates an error message to be much more prominent

---

package.json
yarn.lock

What it says on the tin - bumps yarn to latest v1.9.4

chore: bump yarn to v1.9.4

---

src/Project.js
src/__tests__/Project.test.js
src/commands/project/remove.js
src/commands/remove.js
src/commands/workspace/remove.js
src/commands/workspaces/exec.js
src/commands/workspaces/remove.js
src/commands/workspaces/run.js
src/functions/runWorkspaceTasks.js
src/types.js
src/utils/options.js
src/utils/publish.js
src/utils/removeDependenciesFromPackages.js

A whole bunch of people have asked for these. 
**Runs as parallel as possible while respecting the dep graph:** (safest)
```sh
bolt workspaces exec -- cmd
```
**Runs as parallel as possible ignoring the dep graph:** (fastest)
```sh
bolt workspaces exec --parallel -- cmd
```
**Runs sequentially:** (slowest)
```sh
bolt workspaces exec --serial -- cmd
```
I just added this into `runPackageTasks` so anything that runs across all your packages should now support these flags.
I also want to add a `--concurrency <n>` option for setting a limit of max processes to spawn at any given time. I've set up the basis for adding that, but I wasn't sure how I wanted to do it in code yet so I left it out as a TODO.
cc @kayneb

add --serial and --parallel options

---

src/utils/__tests__/yarn.test.js
src/utils/yarn.js

`npm_config_user_agent` seems being overridden by `yarn`.
This PR exposes bolt version via environment variable.

Pass bolt_config_user_agent to env when running install

---

package.json
src/Project.js
src/__tests__/Project.test.js
src/types.js
src/utils/env.js
src/utils/messages.js
src/utils/options.js
yarn.lock

Resolves #196 
---
`--parallel-nodes` is like `--parallel` except it detects when you are in a CI environment which has parallelized nodes and will automatically distribute the task across all the CI nodes.
```sh
CI_NODE_TOTAL=10 CI_NODE_INDEX=0 bolt workspaces exec --parallel-nodes -- babel src -d lib
```
Will output:
```
info Task is being split across 10 nodes. Current node running across 14 of 137 workspaces
(@scope/component-a) $ babel src -d dist src/index.js -> dist/index.js
(@scope/component-a) $ babel src -d dist src/ComponentA.js -> dist/ComponentA.js
(@scope/component-b) $ babel src -d dist src/index.js -> dist/index.js
(@scope/component-b) $ babel src -d dist src/ComponentB.js -> dist/ComponentB.js
...
Done in 6.49s.
```
That means you can run these scripts across machines and …

Add --parallel-nodes flag

---

src/commands/project/run.js

Fixes #209.
I updated project/run.js to behave the same as run.js. No tests exist at this stage for `bolt run` or `bolt project run`, I can look into adding them if required.

Fix project run throwing invalid error

---

README.md
src/commands/project/run.js
src/commands/run.js
src/commands/workspace/__tests__/run.test.js
src/commands/workspace/run.js
src/commands/workspaces/run.js

Thanks heaps for the patience everyone!
The solution I ended up going with is basically what was outlined [here](https://github.com/boltpkg/bolt/issues/90#issuecomment-451311413)
With each of these ways to run a script
```
bolt foo
bolt run foo
bolt p run foo
bolt w @dovetail/bar run foo
bolt ws --only="@dovetail/bar" run foo
bolt ws exec --only="@dovetail/bar" -- yarn foo
```
The way you would now pass flags is exactly as you'd expect
```
bolt foo --flag1 --flag2=5
bolt run foo --flag1 --flag2=5
bolt p run foo --flag1 --flag2=5
bolt w @dovetail/bar run foo --flag1 --flag2=5
bolt ws exec --only="@dovetail/bar" -- yarn foo  --flag1 --flag2=5
```
The only different one is the `ws run` command
```
bolt ws --only="@dovetail/bar" run foo -- --flag1 --flag2=5
```
The things we are trading off …

Fixes #90 by passing flags down as args for run commands

---

package.json
src/Config.js
src/__tests__/Config.test.js
yarn.lock

This PR fixes a couple of issues with bolt - 
- Bolt is opinionated about the line endings style – it always uses `\n` to denote line endings. This PR enables bolt to automatically detect line endings style (`\n` vs `\r\n`) using `detect-newline` and preserve the style when updating / writing to a package.json file
- Whenever bolt writes a package.json, it now adds a newline character to the last line, in accordance with the [POSIX definition of a line](https://stackoverflow.com/a/729795/3210476).
Note that these issues have already been fixed by `npm` ([here](https://github.com/npm/npm/pull/19904)) and `yarn` ([here](https://github.com/yarnpkg/yarn/commit/05bf97728cbe92f034f7d4596830f481a65fe8fa)), and this just brings bolt's implementation on par.
When using prettier or an opinionated …

Add new line to the end of file, preserve line endings style

---

src/utils/yarn.js

Fixing this warning
```
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
```

Get rid of yarn run -- warning

---

src/utils/__tests__/npm.test.js
src/utils/npm.js

Fixes https://github.com/boltpkg/bolt/pull/190#issuecomment-499965466
The problem with the original fix is that it makes the same mistake Yarn did by overwriting all registry configs. So I changed this to do the minimal amount of work to revert Yarn's incorrect behavior.
Note: Setting an env variable to `undefined` just completely eliminates it, which will cause npm to use its default behavior. Only when `npm_config_registry` has been set to something other than `registry.yarnpkg.com` should we respect it.

Fix fix for yarn setting an npm_config_registry

---

src/commands/__tests__/install.test.js
src/commands/install.js
src/utils/__tests__/yarn.test.js
src/utils/yarn.js

#237
refactored internally as an enum to be a better domain language than a set of booleans. Also those options are competing so we should have only one.
No regression from before, `--pure-lockfile` still works as expected.

feat: allow passing --frozen-lockfile to yarn

---

src/commands/workspace/add.js

This is exactly the same as #67 for the `bolt w X add -D dev-dependency` command.

fix #56 for workspaces --dev flag swallows first dependency

---

src/utils/fs.js
src/utils/symlinkPackageDependencies.js

Alternative fix for #207 instead of existing PR #215.
**src/utils/fs.js**
In the `readLink` method there is a comment [here](https://github.com/boltpkg/bolt/blob/master/src/utils/fs.js#L135-L136) stating code was copied from `npm` cli [here]().
The copied code doesn't have a fallback when the file is _not_ a symlink.
However when we look further in `npm` cli. The copied code is used in such a way [here](https://github.com/npm/npm/blob/d081cc6c8d73f2aa698aab36605377c95e916224/lib/utils/gently-rm.js#L273) as there _is_ a fallback similar to what @Bloodb0ne has proposed in #215.
In #215 the `try/catch` is duplicated in `cmdShim` whereas here I simply use the already safe `readLink` method.
~In this PR I also removed the unused `path-is-inside` dependency.~ …

Fix windows compatibility Issue #207

---

src/commands/__tests__/add.test.js
src/utils/__tests__/addDependenciesToPackages.test.js
src/utils/addDependenciesToPackages.js

Fixes #170 
Previously running `bolt add` would not do anything if the package
already existed in the project, behaving differently from `yarn add`.
Now `bolt add` will always rerun `yarn add` when run in the project
context.
Running the command from a workspace will continue to not reinstall the
package if it already exists in the project as the package would simply
be linked from the project.

Fix bolt add not reinstalling packages from the project root

---

src/utils/__tests__/options.test.js
src/utils/options.js

E.g. local file path installs could have @ symbols, especially if the
local path contains the fully scoped package name.
Fixes #239.

Update toDependency util to handle versions containing @ symbols

---

src/utils/__tests__/yarn.test.js
src/utils/yarn.js

Follows on from #198 which added this to the install command. This
should also be added to at least the add command as preinstall yarn
scripts are ran for both install and add.

Add bolt_config_user_agent env var to `yarn add`

---

src/utils/__tests__/addDependenciesToPackages.test.js
src/utils/addDependenciesToPackages.js

We updated the `bolt add` command in the last version to re-run `yarn add` when run from the project root to allow installing new versions of an existing dependency without needing to run `bolt upgrade` which behaves differently (it recursively upgrades transitive deps).
As part of this work, we forgot to also update the versions of the dependency being added in each workspace in the repo. Resulting in version mismatch errors on subsequent runs of bolt until workspace versions were manually updated.

Update workspace versions when running bolt add on an existing dependency in the project root

---

src/__tests__/cli.test.js
src/cli.js
src/commands/__tests__/help.test.js
src/commands/help.js

--help now only displays help information if ran with no commands, i.e.
`bolt --help`.
If a command is passed, e.g. bolt <command> --help`. the `--help` flag will be
passed through to that command and not display help text.
This fixes running npm scripts that have implemented their own flag,
e.g. `yarn run my-script-that-has-a-help-flag --help`
In the future we will implement help information for subcommands that
may handle `bolt <command> --help` as well as `bolt help <subcommand>`.

Implement help command and modify --help behaviour

---

src/Project.js
src/__tests__/Project.test.js
src/utils/messages.js
src/utils/promiseWrapper.js

Fixes #255.
I've also improved the error message to report the number of tasks that failed and any error messages that were in the error (which is most likely going to be none for the cli version since it spawns processes).

Fix --no-bail not throwing when running in default orderMode

---

CHANGELOG.md
package.json
src/GlobalOptions.js
src/__tests__/cli.test.js
src/cli.js
src/utils/logger.js
src/utils/messages.js
src/utils/processes.js
src/utils/yarn.js
yarn.lock

I've created a `globalOptions` singleton to store global flags to prevent passing args down everywhere.
I considered adding `useBasename` as an option as well but didn't think it would be useful enough for the end consumer to add as a flag. We only use it when executing yarn commands.
I also made some other yarn commands print basename and silenced the output of the user agent call we make.

Add --no-prefix global flag to remove command string from spawned output

---

src/commands/__tests__/install.test.js
src/utils/symlinkPackageDependencies.js

Easy to replicate problem. Running bolt once was fine, when using a locally symlinked bin. However, running it again would throw an error. This should fix.
I think this addresses #226.

fix issue where bolt twice would break during bin symlink step

---

src/commands/install.js
src/utils/__tests__/addDependenciesToPackages.test.js
src/utils/__tests__/symlinkPackageDependencies.test.js
src/utils/addDependenciesToPackages.js
src/utils/symlinkPackageDependencies.js

Rather than re-fetch the Project packages, and graph during the for of loop from the install command, simply passing them in saves a ton of time.
Converts the for of loop for symlinking into a Promise.all.
Don't re-create symlinks.
In our project we have ~360 internal packages, and ~370 external.
Before...
After..

updates for faster symlinking

---

src/utils/symlinkPackageDependencies.js

Internal dependency symlinks can become stale if the dependency changes
paths in the repo so its best to always recreate them for robustness.
The performance cost of this change isn't too bad as the majority of the symlinking
slowdown is caused by the .bin symlinking.
---
Locally in atlassian-frontend this takes about 5 seconds longer but the variance between installs can be more than 5 seconds so its hard to measure the performance impact. On CI the performance was the same.
Removing the existing symlink check blows out local installs from ~30s to ~90s which verifies that the bin symlinks are the slowdowns (which makes sense as its symlinking all the bins of the entire project for each package in the repo regardless of its declared dependencies).

Always symlink internal dependencies even if they already exist
