boltpkg/bolt

- src/commands/__tests__/install.test.js
- src/commands/publish.js
- src/utils/logger.js
- src/utils/npm.js
- src/utils/processes.js
> Fix flow types

- src/commands/__tests__/publish.test.js
- src/commands/publish.js
- src/types.js
- src/utils/__mocks__/npm.js
- src/utils/locks.js
- src/utils/npm.js
Havent added tests yet, just wanted to get your opinion.
> Fixes some small issues in publish command

- package.json
- src/Project.js
- src/__fixtures__/nested-workspaces/package.json
- src/__fixtures__/nested-workspaces/packages/bar/package.json
- src/__fixtures__/nested-workspaces/packages/foo/package.json
- src/__fixtures__/nested-workspaces/packages/foo/packages/baz/package.json
- src/__tests__/Project.test.js
- yarn.lock
And some tests for the rest of Project
> Adds Project.getDependentsGraph

- src/Project.js
- src/__fixtures__/nested-workspaces-transitive-dependents/package.json
- src/__fixtures__/nested-workspaces-transitive-dependents/packages/pkg-a/package.json
- src/__fixtures__/nested-workspaces-transitive-dependents/packages/workspace-a/package.json
- src/__fixtures__/nested-workspaces-transitive-dependents/packages/workspace-a/packages/pkg-b/package.json
- src/__fixtures__/nested-workspaces-transitive-dependents/packages/workspace-a/packages/pkg-c/package.json
- src/__tests__/Project.test.js
- src/__tests__/index.test.js
- src/functions/__tests__/getDependentsGraph.test.js
- src/functions/getDependentsGraph.js
- src/index.js
Not sure why I forgot, but here it is.
Would you also mind doing a release after this one?
> Exposes getDependentsGraph public function

- src/utils/locks.js
Fixes the bug found in #19 which wasnt caught due to no tests for locks.js.
Definitely planning on adding them, just not right now if that's okay
> Fixes regression in locks.js

- src/commands/install.js
- src/utils/yarn.js
Originally added this command for the install error which looks like it went away. 
Figured there's nothing to lose adding it there too.
> Quick fix to fix error when .bin dir's don't exist

- index.js
- package.json
- src/Project.js
- src/__fixtures__/nested-workspaces-with-scoped-package-names/package.json
- src/__fixtures__/nested-workspaces-with-scoped-package-names/packages/bar/package.json
- src/__fixtures__/nested-workspaces-with-scoped-package-names/packages/foo/package.json
- src/__fixtures__/nested-workspaces-with-scoped-package-names/packages/foo/packages/baz/package.json
- src/__tests__/Project.test.js
- src/cli.js
- src/commands/workspaces/run.js
- src/types.js
- src/utils/options.js
- src/utils/yarn.js
- yarn.lock
> Adds Project.filterWorkspaces

- src/functions/__tests__/updatePackageVersions.test.js
- src/functions/updatePackageVersions.js
> Returns list of updated packages in updatePackageVersions

- .gitignore
- package.json
- src/Package.js
- src/__fixtures__/package-with-external-deps-installed/node_modules/foo-dep/package.json
- src/__fixtures__/package-with-external-deps-installed/node_modules/global-dep/package.json
- src/__fixtures__/package-with-external-deps-installed/node_modules/project-only-dep/package.json
- src/__fixtures__/package-with-external-deps-installed/package.json
- src/__fixtures__/package-with-external-deps-installed/packages/bar/node_modules/global-dep
- src/__fixtures__/package-with-external-deps-installed/packages/bar/package.json
- src/__fixtures__/package-with-external-deps-installed/packages/foo/node_modules/foo-dep
- src/__fixtures__/package-with-external-deps-installed/packages/foo/node_modules/global-dep
- src/__fixtures__/package-with-external-deps-installed/packages/foo/package.json
- src/commands/__tests__/remove.test.js
- src/commands/normalize.js
- src/commands/project/__tests__/remove.test.js
- src/commands/project/remove.js
- src/commands/remove.js
- src/commands/run.js
- src/commands/workspace/__tests__/remove.test.js
- src/commands/workspace/remove.js
- src/commands/workspaces/__tests__/remove.test.js
- src/commands/workspaces/remove.js
- src/functions/updatePackageVersions.js
- src/utils/__tests__/fs.test.js
- src/utils/fs.js
- src/utils/messages.js
- src/utils/removeDependenciesFromPackages.js
- src/utils/yarn.js
- yarn.lock
```
pyarn remove dep
pyarn project remove dep
pyarn workspace remove dep
pyarn workspaces remove dep
```
> Add pyarn remove commands

- src/utils/removeDependenciesFromPackages.js
> Fix remove yarn.run scripts

- example/package.json
- example/packages/foo/package.json
- src/__fixtures__/nested-workspaces/packages/foo/package.json
- src/commands/workspace/__tests__/run.test.js
- src/commands/workspace/run.js
Just updates to use the yarn.getScript helper.
Added some tests and updated the example folder too.
> Fixes workspace run command

- .babelrc
- src/commands/__tests__/add.test.js
- src/commands/add.js
- src/commands/workspace/__tests__/add.test.js
- src/commands/workspace/add.js
- src/utils/options.js
- src/utils/symlinkPackageDependencies.js
> Fixes adding scoped packages with bolt add and bolt ws add

- package.json
- src/commands/__tests__/publish.test.js
- src/commands/publish.js
Will release a 0.15.0 for this
> Temporarily disables locking during publish

- src/commands/bin.js
- src/utils/yarn.js
implement bin command - **WIP**
> implement bolt bin command

- README.md
added `bolt bin` in commands + update formating
> docs update added bolt bin in commands

- package.json
- src/commands/workspace/__tests__/run.test.js
- src/utils/__tests__/yarn.test.js
- src/utils/yarn.js
- yarn.lock
Fixes https://github.com/boltpkg/bolt/issues/53
> added yarn as dependency and running locally installed yarn

- package.json
- src/commands/workspace/__tests__/run.test.js
- src/utils/__tests__/yarn.test.js
- src/utils/yarn.js
- yarn.lock
> Revert "added yarn as dependency and running locally installed yarn"

- package.json
- src/commands/workspace/__tests__/run.test.js
- src/utils/__tests__/yarn.test.js
- src/utils/yarn.js
- yarn.lock
Fixes https://github.com/boltpkg/bolt/issues/53
> Run local yarn implementation 2

- package.json
- src/Project.js
- src/utils/messages.js
- yarn.lock
I just left a bunch of stuff commented out for now cause I'll want to return to this.
> Switch to graph-simple-sequencer

- src/cli.js
Fixes https://github.com/boltpkg/bolt/issues/76
> up as an alias to upgrade

- README.md
Reference  - https://github.com/boltpkg/bolt/issues/88
✅ -> ready
❌ -> not implemented yet
🖌 -> implemented but some default options are missing ( so in progress 😕 )
> added status of bolt command to readme

- src/cli.js
- src/commands/__tests__/link.test.js
- src/commands/__tests__/unlink.test.js
- src/commands/link.js
- src/commands/unlink.js
- src/commands/workspace/__tests__/link.test.js
- src/commands/workspace/__tests__/unlink.test.js
- src/commands/workspace/index.js
- src/commands/workspace/link.js
- src/commands/workspace/unlink.js
- src/utils/messages.js
- src/utils/yarn.js
Test cases are pending, and minor refactor. but ready for initial review
> bolt 🔗 and !🔗 command

- src/commands/info.js
- src/utils/yarn.js
- bolt info package-name
- bolt info package-name --json
> bolt info implementation

- .gitignore
- README.md
- src/commands/__tests__/init.test.js
- src/commands/init.js
- src/utils/options.js
- src/utils/yarn.js
added support for flags in bolt init.
> added support for flags to bolt init

- src/Project.js
People keep calling them errors ;P
> Change cycles message to be a warning instead of error

- src/__tests__/Project.test.js
I thought the change was too small to bother waiting for the build, my bad
> Fixing broken test

- src/commands/add.js
> [minor] Removing unused duplicate method

- src/commands/workspace/__tests__/run.test.js
- src/utils/yarn.js
Wasn't caught it tests or local testing because I was always running from within the project.
Apologies.
> Fixes calculation of yarn relative path

- README.md
> Adds an update to readme

- src/commands/__tests__/login.test.js
- src/commands/__tests__/logout.test.js
- src/commands/login.js
- src/commands/logout.js
- src/utils/npm.js
Need clarification:
There is no argument for login and logout. So shall we remove `LoginOptions` and `toLoginOptions`?
> Implemented login and logout

- package.json
- src/commands/__tests__/init.test.js
- src/commands/init.js
- src/utils/__tests__/jsonModifier.js
- src/utils/__tests__/jsonModifier.test.js
- src/utils/__tests__/prompts.test.js
- src/utils/jsonModifier.js
- src/utils/prompts.js
- yarn.lock
> Adding workspace in init

- src/commands/config/__tests__/get.test.js
- src/commands/config/get.js
> adds config get

- .gitignore
- src/commands/__tests__/install.test.js
- src/commands/install.js
- src/utils/__tests__/yarn.test.js
- src/utils/yarn.js
> Prefix npm_config_user_agent env var set by yarn with bolt version

- src/functions/getWorkspaces.js
> Add filtering to getWorkspaces function

- src/commands/publish.js
Tested manually on my local machine
Will add a test in a follow up PR
> Fixes publish command to not include private packages

- src/Package.js
- src/__fixtures__/workspace-with-bin/package.json
- src/__fixtures__/workspace-with-bin/packages/bar/bin.js
- src/__fixtures__/workspace-with-bin/packages/bar/package.json
- src/__fixtures__/workspace-with-bin/packages/foo/package.json
- src/commands/__tests__/install.test.js
- src/commands/install.js
This is simply finishing up #157 . It was a bit out of date.
I thought it would also fix  _ #187 _ but this just solves the cross linking problem, it doesn't make them accessible at the root.
> Fix issue with cross-dep bins not symlinking

- src/__fixtures__/nested-workspaces-with-muliple-binaries/package.json
- src/__fixtures__/nested-workspaces-with-muliple-binaries/packages/bar/package.json
- src/__fixtures__/nested-workspaces-with-muliple-binaries/packages/foo/package.json
- src/__fixtures__/nested-workspaces-with-muliple-binaries/packages/foo/packages/baz/package.json
- src/__fixtures__/nested-workspaces-with-muliple-binaries/packages/zee/package.json
- src/commands/__tests__/publish.test.js
- src/commands/install.js
- src/utils/__tests__/symlinkPackagesBinariesToProject.test.js
- src/utils/messages.js
- src/utils/symlinkPackageDependencies.js
- src/utils/symlinkPackagesBinariesToProject.js
Fixes #187 
* Adds symlinking of package binaries to the project at install time.
* Removes check that all project bin symlinks must point to project node_modules
* Fixes some publish tests
> Adds symlinking of package binaries to the project at install

- src/utils/yarn.js
> Remove quotes around `yarn upgrade` args

- .travis.yml
- bin.js
Updates bin.js as requested in #243
> Drop node v4 support and require v6 at minimum

- package.json
- src/Config.js
- src/commands/__tests__/create.test.js
- src/commands/__tests__/outdated.test.js
- src/commands/__tests__/pack.test.js
- src/commands/__tests__/why.test.js
- src/commands/cache/__tests__/clean.test.js
- src/commands/cache/__tests__/dir.test.js
- src/commands/cache/__tests__/list.test.js
- src/commands/cache/index.js
- src/commands/global/index.js
- src/commands/licenses/__tests__/generateDisclaimer.test.js
- src/commands/licenses/__tests__/list.test.js
- src/commands/licenses/index.js
- src/commands/owner/index.js
- src/commands/project/run.js
- src/commands/project/upgrade.js
- src/commands/publish.js
- src/commands/tag/index.js
- src/commands/team/index.js
- src/functions/__tests__/updatePackageVersions.test.js
- src/utils/__mocks__/spawn.js
- src/utils/__tests__/npm.test.js
- src/utils/npm.js
- src/utils/publish.js
- yarn.lock
The current version of prettier (1.7.0) had a bug that was breaking the pre-commit hook so I've upgraded it to the latest.
> Upgrade prettier to latest

- src/utils/__tests__/addDependenciesToPackages.test.js
- src/utils/addDependenciesToPackages.js
Fixes #274.
I've ran into this a bunch of times but have never got around to fixing it.
> Fix workspace versions not resolving when installed via dist tag
